### ISSUE TITLE
Impossible to refresh cached images manually ? How many time before update ?

### ISSUE THREAD

**Issue by Maxildan** [andrieslouw/imagesweserv#159] opened 2018-09-24 01:58 UTC
Hello all,
I just changed some pictures on my FTP few hours ago and there is no changes on my website. How many time before cached picture refresh ? can we force it manually ?

thx :)

**Comment by andrieslouw** [comment] 2018-09-24 06:33
See #14 , currently this isn't possible to force manually. In our wiki are some details about the time we cache things:https://github.com/weserv/images/wiki/Caching-of-resized-images-(server-side-caching)

Unfortunately, we cannot run our service without caching. But as you can see in #14 , we're working oj a reliable solution to delete images from all our caches.

**Comment by andrieslouw** [comment] 2018-09-24 14:24
Duplicate of #14

**Closed as completed by andrieslouw** 2018-09-24 14:24 UTC
Labels: duplicate, question
