### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by Smorvel** [andrieslouw/imagesweserv#352] opened 2022-08-02 11:01 UTC
https://images.weserv.nl/?url=http://joyreactor.cc/apple-touch-icon.png
For some reason I get 404 eror

**Comment by kleisauke** [comment] 2022-08-02 11:10
Duplicate of #339

**Closed as not planned by kleisauke** 2022-08-02 11:10 UTC
Labels: wontfix

**Comment by Smorvel** [comment] 2022-08-02 11:22
@kleisauke ok, so why this https://images.weserv.nl/?url=http://joyreactor.com/apple-touch-icon.png also doesen't work? domain is .com

**Comment by kleisauke** [comment] 2022-08-02 13:01
Please see https://github.com/weserv/images/issues/285#issuecomment-828176654.
