### ISSUE TITLE
Support of data in URL parameter

### ISSUE THREAD

**Issue by Heziode** [andrieslouw/imagesweserv#246] opened 2020-09-28 22:15 UTC
Hi,

Is it possible to support something like this (the URL base64 encoded is the obtained from [lichtenstein.jpg](https://images.weserv.nl/?url=images.weserv.nl/lichtenstein.jpg&crop=100,100,720,530&encoding=base64) ): 

```
https://images.weserv.nl/?url=data:image/jpeg;base64,/9j/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABkAGQDASIAAhEBAxEB/8QAHAAAAQUBAQEAAAAAAAAAAAAAAAEDBQYHBAII/8QAPBAAAgEDAwICBgcFCQEAAAAAAQIDAAQRBRIhBjEHQRMUIjJRYRZScXKBkaEjQrGy0RUkMzQ2YmOC4fD/xAAbAQABBQEBAAAAAAAAAAAAAAAGAQIDBAUAB//EACURAAICAQMEAgMBAAAAAAAAAAACAQMEBRESEyExMgYiFCMzcf/aAAwDAQACEQMRAD8Ar9FFFergQFM3ZxEfnT2K4tWlC2zsTjC8fbVfJeEraSahOVmxWFlWe6diR7T5pLABdYZS4zswceYzXXDo04eIyOqKwzgindB0lZ9TuLhpFaNJCufrAd%2BO9eaP9nZg2XZViBrUoWjTOARjIzVc6pkV9Mty/IWQgH/rWk3thDdpuiX2N20A%2BdVXrPRS1gkHoxEI5/aJ8uKWheL9zneNtjOLR0FwjZPv/Cth0EhrRSpyCmayu80G7tZhImHXPxrUumlC2Fvk94xRJo9nG6VMjU6/1RJLV5r0RikxRaDImBRS4opxwtFesCggCmj9hHIC5FRNwy3N8kLglIzvOB3%2BVdWpXHoISw7k4A%2BdcFtKsCAZLPnLN9Y/ChfXs%2BUTpL5k2tKxt56jD2tzKPSSwswXZ7KtTPTCPCDJOCGzzjjJPeue9ZXYRNli7YwDnAqQdGuy4jcRoi7gO2aE1N9iVhmdDgYyr7UGf1qL6tnlvbGd5igZQGIA9407BO1rayuyCQSLgMfL51EajdtcQyKWyGTHapOXgihJmTgiSG4jdnf9zKD4V19OXyoRasS3GUbtn5VXUdov2eSBsxnzpYJGjkiYEna25MfwrRx7prsh4IbK%2BayrGjod65HIpa5NJnWe2jkXjemfxrtwKOce5bU5QC1tfF%2BJ5or1gUVMVz1ikcgd69Dmua%2BmjhjLyOFUdyagyLemnInqXk%2BxF6hIZbwInJjOTmmVZXux2wRnFcWr65pFjGA1yjTbSXKtkk1WrjrqCBHaC3aY7M7nGMV5vfNuTdNk%2BAxqlKa%2BMFlaGR9QeRMqF7AVJ2INzdqhO0IGBXOM1mUHiJqkIXZDCTjPtDv/APYrji8QNbjnlYPES2e60/8AHmY7C9WDZZlHq5QSArjnjtUG0DftBg48vnWdP4ka%2BYhGVgIOc8Yrw3XmuG2VjFbADsfRV04zMdFvEt11b43MOdreznzFccYZZgwXB8yTwKrP021B5leZIZAvGEGM132vU2mzoVmiaOQnIO3irfT28EHKS%2BdMalmU2shXcTlCOPw/h%2BVWyMhlzkVmWkX1jcXsctvOhZOwDd60SwnWVRtfIIyOK3tHyZj9bGTqVMe8HTRRRREYp6Xiq91zBJcaNcohYMY8gj41Y8Cmp4FnjaN8EEYqG%2BrqJKklb8J3PnHb6W89FPOELHmRu4FLqVmlvu23cUyk5Gxv0rYdV6G0y5LOtusZbzj9nFQd34dK%2B2eK8gjgRclZZQDmhHKwpxO7BLj5C3eDMI4RgMdoPvZz9vH60GDam5mVh5ADtXu6Hq9w6EhlRmx8xTLyHdgbu%2BMCq8dywOJCqTRu4QkH97O01O6pqt9qGnR6attDFCxBHo4fh35quMkzqRtkfPY4zWm%2BHmudNaToBbXdIubm5DlRkcCorpateWwqTynYzWW1kt5yhIUg5PFNkLgDa2fM/EVZ9Y0u4vvWtcsrN1tGkJIIPs1DWtnLckRQ7mcHCjuSPsqemZsj6%2BRj9u8niBo1LSxAxPu4UZz%2Bla54XXclxpC75HchtpLVAdP9BGeFXupZcMMsgXAH41f%2BnNBt9Hh9FbrsXOe%2Ba29PwLa7eq3gysvJR04wTRAopaKIDFEr0vFJilrjhJDtTtmqV1ZYw6xIkXrzWxjYqdp71dH9xs1CqtomokNAjNnJLChv5A3GuDc0hd3Mp6%2B0vTdOtrOKyn9JNhjIQPeqL6P0U65qsVrIWCNljt94471qHiV01aX2nf2qJYVuI3SJLdRhnz3OK0Lwkfwt6e0OxvL9lfVkXZNE3LLIe/AFD1OTwmI23NmxIhZkrdr0FHp2lRTy2aJABlXbBH51x6hp623o4hZRzqzZ5UVsnUvXHTqQoy2kk8DkFYimO/lg8Vm/WmuRalexPDZG2RFyO3J/CrNmoX31NDJMFWutUdZiSpdVW199ELyKG1gigC7mUMRn8qoHQNzEutehYEl12%2B7wPnnvWna3c56XvtzH/BYYrJuikx1RAQhwG%2BfPs0mmt%2BxSXK9GN6sEVbdcAH2fM08SB2FNWZ/u6fdpxqO19QRafsIaKMUU4aLijFeqMUhx4lGEaq3cs5v224Xyy1WWYZRqr86b7xgwyM5zQv8AIp%2Bim/o3mSJ9d04eJmlNq9wI7KKMGRnOAT5GuPQE0671vVrqzHpYJJ8qWUZx7XY9/IVXPFmLGtQITtJiXOBkGn/DG7axsrmX1Q3ZjcNsVwMnnjk/Z%2BVZenVRy32L%2BW0ynYstxqt8%2BpCyEjvB6UqHZeRjtU5LG/q6GXh8dj%2BH9a4bTxQns2lt06AtpC/YvGSQfjRaape6rHNPc6cbEfuKOc9//KZzshLIZZganF2XaRnXSPo1fN/xGs16IA%2BklqCxbJYnv9X/AMrS%2BoiB0zeccGKs36HU/SO2559r%2BU/1pNP/AKr/AKSZPoxu1kM26fdpxhXiyBFuufq06wzR%2BvqCLew3iivVFKNCloopooknuNUEWJ1Bh/vxRRQz8i9VN/RvMmd%2BLvGvwj4RLUj4UxRvbSkoBhvKiiqmleyk%2BZ6SXtrWAy7/AES5p66hjWDaoKjd5GiitDVI2pkp4M72qVvqbjpu988RedZz0J/qW3%2B638tFFYeB/RTVy/Rjd7X/AC6/dp2iijxfUE29hMCiiinjD//Z
```

**Comment by andrieslouw** [comment] 2020-09-29 16:57
Please see https://github.com/weserv/images/issues/234#issuecomment-651392161

**Comment by kleisauke** [comment] 2021-01-10 15:23
Closing as duplicate of #234.

**Closed as completed by kleisauke** 2021-01-10 15:23 UTC
Labels: enhancement
