### ISSUE TITLE
ICOs do not use the correct icon size

### ISSUE THREAD

**Issue by dgxo** [andrieslouw/imagesweserv#389] opened 2023-09-19 22:22 UTC
I use wsrv for a link preview thing on my website, and Discord uses an ico file for their image meta tag, which was passed into wsrv.nl, but it returned a very low resolution image upscaled to 100x100.

Seems like it selects the lowest quality (or the first) icon from the ico file to use and scale.

For example, [Discord's image ico](https://discord.com/assets/ec2c34cadd4b5f4594415127380a85e6.ico) is usually high quality, but the [resized version](https://wsrv.nl/?url=https://discord.com/assets/ec2c34cadd4b5f4594415127380a85e6.ico&w=200&h=200&fit=cover) is very low res, and just upscaled, looking really ugly.

Maybe either the highest quality icon is selected, or probably depending on processing times maybe using the closest size that's larger than the target.

**Comment by kleisauke** [comment] 2023-10-05 13:23
Duplicate of #170

**Closed as completed by kleisauke** 2023-10-05 13:23 UTC
Labels: question
