### ISSUE TITLE
Hello, the reverse imgur failed.

### ISSUE THREAD

**Issue by OuOumm** [andrieslouw/imagesweserv#405] opened 2024-01-15 09:04 UTC
url：https://wsrv.nl/?url=https://i.imgur.com/n1jWucc.png

error：{"status":"error","code":404,"message":"The requested URL returned error: 429"}

**Comment by kleisauke** [comment] 2024-01-15 16:59
Duplicate of #319

**Closed as not planned by kleisauke** 2024-01-15 16:59 UTC
