### ISSUE TITLE
webp and apple safari  & chrome fallback to jpg

### ISSUE THREAD

**Issue by amgmbs** [andrieslouw/imagesweserv#236] opened 2020-06-26 14:20 UTC
Congratulations for this amazing service and code!

Would it be possible to add fallback for apple not being able to show webp images?

This is "invisible" on macs

https://images.weserv.nl/?url=images.weserv.nl/lichtenstein.jpg&w=300&h=300&output=webp

Thank you all!

**Comment by andrieslouw** [comment] 2020-06-29 21:51
Thanks for the suggestion, but please see #214 
Due to the Cloudflare caching it is technically impossible to do so for us.

**Comment by kleisauke** [comment] 2021-01-10 15:26
Duplicate of #214, closing.

**Closed as completed by kleisauke** 2021-01-10 15:26 UTC
Labels: duplicate, enhancement, wontfix
