### ISSUE TITLE
Unresolvable hostname (blocked by policy) for cosmetica.cc

### ISSUE THREAD

**Issue by Bitslayn** [andrieslouw/imagesweserv#394] opened 2023-10-27 23:11 UTC
Having the same issue with [https://cosmetica.cc](https://cosmetica.cc).
One such image is [https://cosmetica.cc/page/splash/Eyezah-Bottom-2.jpg](https://cosmetica.cc/page/splash/Eyezah-Bottom-2.jpg).
If you could whitelist my domain that would be great, thanks!

_Originally posted by @eyezahhhh in https://github.com/weserv/images/issues/286#issuecomment-1758881589_

**Comment by Bitslayn** [comment] 2023-10-27 23:13
Other links which are found on https://modrinth.com/mod/cosmetica include:
https://wsrv.nl/?url=https%3A%2F%2Fcosmetica.cc%2Fpage%2Fsponsorships%2Fzap%2Fbanner-2.jpg&n=-1
https://wsrv.nl/?url=https%3A%2F%2Fcosmetica.cc%2Fpage%2Fdean-norris.png&n=-1

**Comment by kleisauke** [comment] 2023-10-28 09:06
Duplicate of #339

**Closed as not planned by kleisauke** 2023-10-28 09:06 UTC
Labels: wontfix
