### ISSUE TITLE
Cloudflare 522 error though the image is accessible

### ISSUE THREAD

**Issue by ndavoust** [andrieslouw/imagesweserv#156] opened 2018-09-18 08:52 UTC
Hi,

We encounter cloudflare 522 errors on some urls (exemple https://images.weserv.nl/?url=uploadcaregdc.s3-eu-west-1.amazonaws.com%2F7072f6d8-d2bb-4ce8-82ee-cc29a0ec8967.stretch_fill.setfill_ffffff.resize_1123x842.preview_800x600.preview_800x800.jpg )

Whereas the image is properly accessible:
https://uploadcaregdc.s3-eu-west-1.amazonaws.com/7072f6d8-d2bb-4ce8-82ee-cc29a0ec8967.stretch_fill.setfill_ffffff.resize_1123x842.preview_800x600.preview_800x800.jpg

Other image renders properly but without crop parameters fails too:
OK => https://images.weserv.nl/?url=uploadcaregdc.s3-eu-west-1.amazonaws.com%2F936e726a-3318-454f-adc4-881fac9b65a0.stretch_fill.setfill_ffffff.resize_1182x887.preview_800x600.preview_800x800.JPG&t=squaredown&w=362&h=0

FAIL => https://images.weserv.nl/?url=uploadcaregdc.s3-eu-west-1.amazonaws.com%2F936e726a-3318-454f-adc4-881fac9b65a0.stretch_fill.setfill_ffffff.resize_1182x887.preview_800x600.preview_800x800.JPG

Have you any idea how to fix it?

Thanks!

**Comment by andrieslouw** [comment] 2018-09-18 09:10
Looks like #109 happened again: IPv6-stack flipped, will research, temporary fix implemented.

**Comment by andrieslouw** [comment] 2018-09-18 09:20
Duplicate of #157

**Closed as completed by andrieslouw** 2018-09-18 09:20 UTC
Labels: bug

**Comment by ndavoust** [comment] 2018-09-18 10:01
Thanks for the quick response, but still not working or not working again  unfortunately :-(

**Comment by andrieslouw** [comment] 2018-09-18 10:43
It was not working again indeed, currently hot-fixing the IPv6-issues, but this didn't work as intended, I'm sorry..
