### ISSUE TITLE
Online service down

### ISSUE THREAD

**Issue by ebaynaud** [andrieslouw/imagesweserv#155] opened 2018-09-18 08:42 UTC
Cannot access to https://images.weserv.nl/?url=ssl:avatars2.githubusercontent.com/u/1921301

**Comment by andrieslouw** [comment] 2018-09-18 09:10
Looks like #109 happened again: IPv6-stack flipped, will research, temporary fix implemented.

**Comment by andrieslouw** [comment] 2018-09-18 09:21
Duplicate of #157

**Closed as completed by andrieslouw** 2018-09-18 09:21 UTC
Labels: bug
